package example.testbxmsgit;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Testdomain implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.Integer age;
   private java.lang.String state;
   private java.lang.String price;

   public Testdomain()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.lang.String getState()
   {
      return this.state;
   }

   public void setState(java.lang.String state)
   {
      this.state = state;
   }

   public java.lang.String getPrice()
   {
      return this.price;
   }

   public void setPrice(java.lang.String price)
   {
      this.price = price;
   }

   public Testdomain(java.lang.String name, java.lang.Integer age,
         java.lang.String state, java.lang.String price)
   {
      this.name = name;
      this.age = age;
      this.state = state;
      this.price = price;
   }

}